import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StoreProvider } from "./store/storeProvider";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout } from "antd";
import AppHeader from "./components/AppHeader";
import AppSideMenu from "./components/AppSideMenu";
import Sider from "antd/es/layout/Sider";
import { Content } from "antd/es/layout/layout";
import { Typography } from "antd";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import { setRequestLocale } from "next-intl/server";
 
export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}
 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  
  const messages = await getMessages();
  
  return (
    <StoreProvider>
      <Typography>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
        <AntdRegistry> 
          <Layout>
          <AppHeader/>
          <Layout hasSider>
          <Sider theme="light" style={{
            position:"fixed",
            top:"64px",
            left:0,
            borderRight:"1px solid #f1f1f1",
            height:"calc(100vh - 64px)",
          }}>
            <AppSideMenu />
          </Sider>
          <Layout style={{marginLeft:"200px"}}>
            <Content style={{padding:"16px", minHeight:"calc(100vh - 64px)"}}>{children}</Content></Layout>
          </Layout>
          </Layout>
          </AntdRegistry>
        </body>
    </html>
    </Typography>
    </StoreProvider>
  );
}