import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StoreProvider } from "./store/storeProvider";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout } from "antd";
import AppHeader from "./components/AppHeader";
import AppSideMenu from "./components/AppSideMenu";
import Sider from "antd/es/layout/Sider";
import { Content } from "antd/es/layout/layout";
import { Providers } from "./providers";
import { I18nProviderClient } from "../locales/client";
import { Typography } from "antd";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  }
}>) {
  return (
    <StoreProvider>
      <Typography>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <I18nProviderClient locale={params.locale}>{children}</I18nProviderClient>
        <AntdRegistry> 
          <Layout>
          <AppHeader/>
          <Layout hasSider>
          <Sider theme="light" style={{
            position:"fixed",
            top:"64px",
            left:0,
            borderRight:"1px solid #f1f1f1",
            height:"calc(100vh - 64px)",
          }}>
            <AppSideMenu />
          </Sider>
          <Layout style={{marginLeft:"200px"}}>
            <Content style={{padding:"16px", minHeight:"calc(100vh - 64px)"}}>{children}</Content></Layout>
          </Layout>
          </Layout>
          </AntdRegistry>
        </body>
    </html>
    </Typography>
    </StoreProvider>
  );
}
